### ISSUE TITLE
[FEAT] [03-03] 액세스 토큰을 전달받으면, 백엔드 서버는 액세스 토큰을 통해 해당 서비스의 리소스 서버에 사용자 정보를 요청한다.

### ISSUE THREAD

**Issue by SongJSeop** [boostcampwm2023/web16-B1G1#21]
## ✨ 기능 설명

[BE] [03-03] 액세스 토큰을 전달받으면, 백엔드 서버는 액세스 토큰을 통해 해당 서비스의 리소스 서버에 사용자 정보를 요청한다.

## ✨ 개발 목록

- [ ]

**Comment by qkrwogk** [comment]
- 다음 이슈로 통합됨
  - #105 [03-05] 서버는 구글로 로그인 기능을 제공한다.
  - #106 [03-06] 서버는 네이버로 로그인 기능을 제공한다.
  - #107 [03-07] 서버는 GitHub으로 로그인 기능을 제공한다.
