### ISSUE TITLE
[FEAT] [05-03] 로그인을 하지 않은 사용자의 요청이라면 BadRequest 에러를 반환한다.

### ISSUE THREAD

**Issue by qkrwogk** [boostcampwm2023/web16-B1G1#34]
## ✨ 기능 설명

[BE] [05-03] 로그인을 하지 않은 사용자의 요청이라면 BadRequest 에러를 반환한다.

## ✨ 개발 목록

- [ ]

**Comment by SongJSeop** [comment]
로그인 여부 상관 없이 쿠키 삭제 예정
